### ISSUE TITLE
GoogleVault

### ISSUE THREAD

**Issue by lmodlinski** [knime-pg/google-analytics#1]
Hey,

I've wanted to use this plugin but I struggle to find where com.pg.knime.vault.GoogleVault is located. I always fall into ..catch clause in GoogleApiConnectorNodeConfiguration constructor and - in consequence - no real vault is created so I can actually connect to Google API for Analytics.

I've forked and quickfix'd it so it is usable now but maybe I am missing something with the mentioned Vault class.

Greetings

**Comment by ckevinhill** [comment]
It’s a bit cludgy but the “Vault” classes are how I store the confidential keys used by the APIs.  Below is an example of the Vault implementation:

package com.pg.knime.vault;

import com.pg.knime.secure.DefaultVault;

public class GoogleVault extends DefaultVault {

private static final String DEFAULT_CLIENT_ID = "XXXXXXXXXXXX.apps.googleusercontent.com";
       private static final String DEFAULT_CLIENT_SECRET ="DEFAULT_CLIENT_SECRET";

       private static final String GA_USER_TOKEN = "USER_TOKEN_GA";

       public GoogleVault() {

              addKey("DEFAULT_CLIENT_ID",       DEFAULT_CLIENT_ID);
              addKey("DEFAULT_CLIENT_SECRET", DEFAULT_CLIENT_SECRET);

              addKey("TOKEN_TYPES", arrayToString("Google Analytics") );
              addKey("USER_TOKENS", arrayToString(GA_USER_TOKEN) );

       }
}

If you create a class like the above in your project (or in a referenced project) you can then update the GoogleApiConnectorNodeConfiguration loads your class (i.e. if you don’t name it com.pg.knime.vault.GoogleVault).  Or you can just hardcode the values where the Vault wrapper is called (since all it is doing is passing along values).

Hope that helps!

Cheers,

Charles Kevin Hill (丘凯文)
GBS Consumer Solutions – eBusiness Analytics
(m) 513.293.5419
(f)  513.277.6702

[ebusiness-logo-small]
